import assert from "node:assert/strict";
import test from "node:test";
import * as api from "../dist/index.js";
const hash=(v)=>api.sha256Hex(api.stableStringify(v));
const revision=api.createAutomationRevisionV1({automation_id:"automation-s3",tenant_id:"tenant-a",revision:1,purpose:"admin",target_mode:"PINNED",pinned_target:{target_ref:{entity_kind:"workflow",entity_id:"workflow-a",revision:1,fingerprint:hash("workflow")}},definitions:[],external_refs:{agent_refs:[],workforce_refs:[],workflow_refs:[],resource_refs:[],executor_refs:[]},delegation_requirement_refs:[],governing_refs:[],authored_configuration:{secret_token:"never-on-wire"},authored_by:"test",authored_at:1,change_reason:"test",provenance_refs:[]});
const head=api.createAutomationHeadV1(revision,1);
const identity=api.createActivationCausalIdentityV1({tenant_id:"tenant-a",automation_ref:revision.ref,source:{kind:"system",system_id:"s3",occurrence_key:"one",purpose:"admin"}});
const observed=api.validateActivationStateEventV1({schema_version:api.ACS_NATIVE_SCHEMA_VERSION,activation_state_event_id:"activation-s3-observed",activation_id:identity.activation_id,tenant_id:"tenant-a",sequence:1,to_state:"observed",cause_digest:hash("cause"),observed_automation_lifecycle:"draft",occurred_at:2,provenance_refs:[]});
const core={async listAutomationHeads({tenantId}){return tenantId==="tenant-a"?[head]:[]},async getAutomationLineage(id){if(id!==head.automation_id)throw Error("missing");return {head,revisions:[revision],lifecycleEvents:[]}},async listDelegationGrantHeads(){return[]},async getDelegationGrantLineage(){throw Error("missing")},async getActivationLineage(id,tenant){if(id!==identity.activation_id||tenant!=="tenant-a")throw Error("missing");return {head:api.createActivationHeadV1(identity,observed),stateEvents:[observed],attempts:[]}}};
const auth=(tenantId="tenant-a")=>api.createAcsAuthContext({mode:"mock",actorType:"user",actorId:"dev-operator",tenantId,authenticated:true,trusted:true});
function context(){return api.createControlPlaneContext({nativeCore:core,tenantId:"tenant-a",tenantMemberships:[{tenantId:"tenant-a",subjectId:"member",status:"active"}]});}
const get=(path,ctx,a=auth())=>api.routeProductApiRequest({method:"GET",url:path,headers:{}},path,ctx,{auth:a,correlationId:"s3"});
test("S3 Product API uses S2 safe administrative projections on the wire",async()=>{const ctx=context();try{const current=await get("/api/v1/automations/automation-s3",ctx);const exact=await get(`/api/v1/automations/automation-s3?revision=1&fingerprint=${revision.ref.fingerprint}`,ctx);const observedResult=await get(`/api/v1/activations/${identity.activation_id}?observationDigest=${observed.cause_digest}`,ctx);const mismatch=await get("/api/v1/automations/automation-s3?revision=1&fingerprint=bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",ctx);const foreign=await get("/api/v1/automations/automation-s3",ctx,auth("tenant-b"));assert.equal(current.status,200);assert.equal(exact.status,200);assert.equal(observedResult.status,200);assert.equal(current.body.data.metadata.source.addressing,"CURRENT");assert.equal(exact.body.data.metadata.source.addressing,"EXACT");assert.equal(observedResult.body.data.metadata.source.addressing,"OBSERVED");assert.equal(mismatch.status,409);assert.equal(mismatch.body.error.reason,"fingerprint_mismatch");assert.equal(foreign.status,403);assert.equal(JSON.stringify(current.body).includes("never-on-wire"),false);assert.equal(JSON.stringify(observedResult.body).match(/raw delivery|provider-token|lease-value|authority-secret/i),null);}finally{await ctx.close();}});
