import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import test from "node:test";
import { Pool } from "pg";
import * as api from "../dist/native-core/index.js";
import { PostgresSharedAuthoritativeState } from "../dist/control-plane/shared-state/postgres-shared-state.js";

const hash=(v)=>createHash("sha256").update(v).digest("hex");
async function isolated(run){const schema=`e17i04s2_${Date.now()}_${process.pid}`;const admin=new Pool({connectionString:process.env.ACS_SH_DATABASE_URL});const url=new URL(process.env.ACS_SH_DATABASE_URL);url.searchParams.set("options",`-c search_path=${schema}`);const state=new PostgresSharedAuthoritativeState({connectionString:url.toString()});const pool=new Pool({connectionString:url.toString()});try{await admin.query(`CREATE SCHEMA "${schema}"`);await state.migrate();await pool.query("INSERT INTO acs_tenants (tenant_id,revision,payload) VALUES ('tenant-d',1,'{}'::jsonb),('tenant-other',1,'{}'::jsonb)");await run(state,pool)}finally{await state.close().catch(()=>undefined);await pool.end().catch(()=>undefined);await admin.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);await admin.end()}}
const agent=(id)=>({agent_id:id,tenant_id:"tenant-d",revision_ref:{entity_kind:"agent",entity_id:id,revision:1,fingerprint:hash(id)}});
function revision(grant,revision,delegator,delegate,parent,onward=revision===1){return api.createDelegationGrantRevisionV1({grant_id:grant,tenant_id:"tenant-d",revision,delegator:agent(delegator),delegate:agent(delegate),authority_bounds:{actions:["act"],capability_refs:[],resource_refs:[],tool_refs:[],model_refs:[],connection_refs:[],credential_purposes:[],memory_scope_refs:[],memory_operations:[]},valid_from:1,expires_at:1000,onward_delegation_allowed:onward,max_delegation_depth:3,...(parent?{parent_grant_ref:parent,ancestry_grant_refs:[parent],depth:2}:{ancestry_grant_refs:[],depth:1}),governing_authority_refs:[],governing_policy_refs:[],approval_refs:[],provenance_refs:[],issued_by:"governance",issued_at:10,reason:"test"})}
function head(r,lifecycle="active",revokedAt){return api.validateDelegationGrantHeadV1({schema_version:api.ACS_NATIVE_SCHEMA_VERSION,grant_id:r.ref.grant_id,tenant_id:r.ref.tenant_id,current_revision:r.ref.revision,current_fingerprint:r.ref.fingerprint,lifecycle,valid_from:r.valid_from,expires_at:r.expires_at,...(revokedAt?{revoked_at:revokedAt,revocation_reason:"test"}:{}),created_at:10,updated_at:revokedAt??10})}
function event(id,sequence,grant,type="delegation.grant.created"){return api.createEventEnvelopeV2({event_id:id,event_type:type,timestamp:sequence,sequence,organization_id:"org",product_domain:"acs",tenant_id:"tenant-d",subject_type:"delegation_grant",subject_id:grant,actor:{kind:"service",ref:"test"},source:"acs",correlation_id:id,idempotency_key:id,payload:{grant_id:grant}})}
function command(r,key,expectedFingerprint){return {head:head(r),revision:r,expectedHead:r.ref.revision-1,...(expectedFingerprint?{expectedFingerprint}:{}),idempotency:{scope:`delegation.grant:tenant-d:${r.ref.grant_id}`,key,request_hash:hash(key)},event:event(key,r.ref.revision,r.ref.grant_id,r.ref.revision===1?"delegation.grant.created":"delegation.grant.revised"),outboxId:`outbox-${key}`}}

test("Slice 2 PostgreSQL persists Delegation Grant history, CAS, ancestry, revocation, idempotency, and atomicity",{skip:process.env.ACS_SH_DATABASE_URL?false:"ACS_SH_DATABASE_URL is not configured"},async()=>{await isolated(async(state,pool)=>{
  const root=revision("grant-ab",1,"agent-a","agent-b");const created=await state.nativeCore.advanceDelegationGrant(command(root,"ab-create"));assert.equal(created.lineage.revisions.length,1);assert.deepEqual((await state.nativeCore.advanceDelegationGrant(command(root,"ab-create"))).lineage,created.lineage);
  await assert.rejects(()=>state.nativeCore.advanceDelegationGrant({...command(root,"ab-different"),idempotency:{scope:"delegation.grant:tenant-d:grant-ab",key:"ab-create",request_hash:hash("different")}}),api.NativeIdempotencyConflictError);
  const revised=revision("grant-ab",2,"agent-a","agent-b",undefined,true);const second=await state.nativeCore.advanceDelegationGrant(command(revised,"ab-revise",root.ref.fingerprint));assert.equal(second.lineage.revisions.length,2);assert.equal((await state.nativeCore.getDelegationGrantLineage("grant-ab")).revisions[0].ref.fingerprint,root.ref.fingerprint);
  await assert.rejects(()=>state.nativeCore.advanceDelegationGrant(command(revision("grant-ab",3,"agent-a","agent-b"),"ab-stale",root.ref.fingerprint)),api.RevisionConflictError);
  const child=revision("grant-bc",1,"agent-b","agent-c",second.lineage.revisions[1].ref);await state.nativeCore.advanceDelegationGrant(command(child,"bc-create"));await state.nativeCore.assertDelegationGrantPathUsable({grantRef:child.ref,at:20});
  await assert.rejects(()=>state.nativeCore.advanceDelegationGrant({...command({...root,ref:{...root.ref,grant_id:"grant-self"}},"self"),revision:{...root,ref:{...root.ref,grant_id:"grant-self"},delegate:agent("agent-a")}}),api.NativeContractValidationError);
  const expand=api.createDelegationGrantRevisionV1({grant_id:"grant-expand",tenant_id:"tenant-d",revision:1,delegator:agent("agent-c"),delegate:agent("agent-d"),authority_bounds:{...child.authority_bounds,actions:["act","expanded"]},valid_from:1,expires_at:1000,onward_delegation_allowed:false,max_delegation_depth:3,parent_grant_ref:child.ref,ancestry_grant_refs:[second.lineage.revisions[1].ref,child.ref],depth:3,governing_authority_refs:[],governing_policy_refs:[],approval_refs:[],provenance_refs:[],issued_by:"governance",issued_at:10,reason:"expand"});await assert.rejects(()=>state.nativeCore.advanceDelegationGrant(command(expand,"expand")),api.DelegationResolutionError);
  const cycle=api.createDelegationGrantRevisionV1({...expand,grant_id:"grant-cycle",tenant_id:"tenant-d",revision:1,delegator:agent("agent-c"),delegate:agent("agent-a"),authority_bounds:child.authority_bounds,reason:"cycle"});await assert.rejects(()=>state.nativeCore.advanceDelegationGrant(command(cycle,"cycle")),api.NativeDelegationGrantIntegrityError);
  assert.throws(()=>api.createDelegationGrantRevisionV1({...expand,grant_id:"grant-depth",tenant_id:"tenant-d",revision:1,depth:2,reason:"depth"}),api.NativeContractValidationError);
  const cross={...child,ref:{...child.ref,grant_id:"grant-cross",tenant_id:"tenant-other"}};await assert.rejects(()=>state.nativeCore.advanceDelegationGrant({...command(cross,"cross"),head:{...head(cross),tenant_id:"tenant-other"},idempotency:{scope:"delegation.grant:tenant-other:grant-cross",key:"cross",request_hash:hash("cross")},event:{...event("cross",1,"grant-cross"),tenant_id:"tenant-other"}}));
  const before=await pool.query("SELECT (SELECT count(*) FROM acs_delegation_grant_revisions)::int AS revisions,(SELECT count(*) FROM acs_native_events)::int AS events,(SELECT count(*) FROM acs_native_outbox)::int AS outbox");const atomic=revision("grant-atomic",1,"agent-x","agent-y");await assert.rejects(()=>state.nativeCore.advanceDelegationGrant({...command(atomic,"atomic"),outboxId:"outbox-ab-create"}));const after=await pool.query("SELECT (SELECT count(*) FROM acs_delegation_grant_revisions)::int AS revisions,(SELECT count(*) FROM acs_native_events)::int AS events,(SELECT count(*) FROM acs_native_outbox)::int AS outbox");assert.deepEqual(after.rows[0],before.rows[0]);
  const revoked=head(second.lineage.revisions[1],"revoked",30);const revoke=api.createDelegationGrantRevocationV1({revocation_id:"revoke-ab",grant_ref:second.lineage.revisions[1].ref,revoked_at:30,revoked_by:"governance",reason:"test",governing_authority_refs:[],approval_refs:[],provenance_refs:[]});await state.nativeCore.revokeDelegationGrant({head:revoked,revocation:revoke,expectedHead:2,expectedFingerprint:second.lineage.revisions[1].ref.fingerprint,idempotency:{scope:"delegation.grant.revoke:tenant-d:grant-ab",key:"revoke-ab",request_hash:hash("revoke-ab")},event:event("revoke-ab",3,"grant-ab","delegation.grant.revoked"),outboxId:"outbox-revoke-ab"});assert.equal((await state.nativeCore.getDelegationGrantLineage("grant-ab")).revocations.length,1);await assert.rejects(()=>state.nativeCore.assertDelegationGrantPathUsable({grantRef:child.ref,at:40}),api.NativeDelegationGrantIntegrityError);
})});
