import assert from "node:assert/strict";
import test from "node:test";

const api=await import((process.env.ACS_TEST_DIST_ROOT??"../dist")+"/index.js");
const digest="a".repeat(64); const grantRef={grant_id:"grant-bc",tenant_id:"tenant-1",revision:1,fingerprint:digest};
const scope={organization_id:"org",product_domain:"acs",tenant_id:"tenant-1"}; const idempotency={scope:"run:run-1",key:"run-1",request_hash:digest};
const request={run:{run_id:"run-1",scope,idempotency,execution_binding_refs:[],created_at:10},workforce_id:"workforce-1",idempotency,admitted_at:20,delegation_grant_ref:grantRef};
test("Slice 4 admits only after delegated authority resolution and captures an immutable historical authority snapshot",async()=>{let admitted;const nativeCore={async admitWorkforceRun(input){admitted=input;return {run:{run_id:"run-1"},snapshot_id:"membership",members:[],event_id:"event"}}};const resolved={authority_basis:{revision:{ref:grantRef}},chain:[{revision:{ref:{grant_id:"grant-ab",tenant_id:"tenant-1",revision:1,fingerprint:"b".repeat(64)}}},{revision:{ref:grantRef}}],effective_authority:{authority_bounds:{actions:["read"],capability_refs:[],resource_refs:[],tool_refs:[],model_refs:[],connection_refs:[],credential_purposes:[],memory_scope_refs:[],memory_operations:[]},governing_authority_refs:[],governing_policy_refs:[]}};const service=new api.DelegatedWorkforceRunAdmissionServiceV1(nativeCore,{async resolve(){return resolved}});await service.admit(request);assert.deepEqual(admitted.delegated_authority_snapshot.chain_refs,[resolved.chain[0].revision.ref,grantRef]);assert.equal(admitted.delegated_authority_snapshot.authority_basis_ref.fingerprint,digest);assert.deepEqual(admitted.delegated_authority_snapshot.effective_authority_bounds.actions,["read"]);resolved.effective_authority.authority_bounds.actions.push("write");assert.deepEqual(admitted.delegated_authority_snapshot.effective_authority_bounds.actions,["read"])});
test("Slice 4 fails closed before native admission when delegated authority is unusable",async()=>{let admitted=false;const service=new api.DelegatedWorkforceRunAdmissionServiceV1({async admitWorkforceRun(){admitted=true}},{async resolve(){throw new api.DelegationResolutionError("GRANT_NOT_USABLE","revoked")}});await assert.rejects(()=>service.admit(request),api.DelegatedAuthorityAdmissionError);assert.equal(admitted,false)});
test("Slice 4 preserves T1 authority evidence, redacts it, and does not replay a changed snapshot",async()=>{const stored=new Map();let state="valid";let revision=1;const owner={async admitWorkforceRun(input){const prior=stored.get(input.idempotency.key);const serialized=JSON.stringify(input.delegated_authority_snapshot);if(prior){if(prior.serialized!==serialized)throw new api.NativeIdempotencyConflictError(input.idempotency.scope,input.idempotency.key);return prior.result}const result={run:{run_id:input.run.run_id},snapshot_id:"membership",members:[],event_id:"event"};stored.set(input.idempotency.key,{serialized,result,snapshot:input.delegated_authority_snapshot});return result}};const resolver={async resolve(){if(state!=="valid")throw new api.DelegationResolutionError("GRANT_NOT_USABLE","revoked");return {authority_basis:{revision:{ref:{...grantRef,revision}}},chain:[{revision:{ref:grantRef}}],effective_authority:{authority_bounds:{actions:["read"],capability_refs:[],resource_refs:[],tool_refs:[],model_refs:[],connection_refs:[],credential_purposes:[],memory_scope_refs:[],memory_operations:[]},governing_authority_refs:[],governing_policy_refs:[]}}}};const service=new api.DelegatedWorkforceRunAdmissionServiceV1(owner,resolver);const first=await service.admit(request);assert.deepEqual(await service.admit(request),first);const snapshot=stored.get("run-1").snapshot;assert.doesNotMatch(JSON.stringify(snapshot),/"secret"|"token"|"content"|"credential_material"|"raw_authority_provider_payload"/i);state="revoked";await assert.rejects(()=>service.admit({...request,run:{...request.run,run_id:"run-2",idempotency:{...idempotency,key:"run-2"}},idempotency:{...idempotency,key:"run-2"}}),api.DelegatedAuthorityAdmissionError);assert.equal(snapshot.authority_basis_ref.revision,1);state="valid";revision=2;await assert.rejects(()=>service.admit(request),api.NativeIdempotencyConflictError)});
