import assert from "node:assert/strict";
import test from "node:test";

const api=await import((process.env.ACS_TEST_DIST_ROOT??"../dist")+"/index.js");
const hash=(x)=>x.repeat(64); const ref=(id)=>({entity_kind:"agent",entity_id:id,revision:1,fingerprint:hash(id[6]??"a")}); const agent=(id)=>({agent_id:id,tenant_id:"tenant-1",revision_ref:ref(id)}); const bounds=(actions=["read"])=>({actions,capability_refs:[],resource_refs:[],tool_refs:[],model_refs:[],connection_refs:[],credential_purposes:[],memory_scope_refs:[],memory_operations:[]});
function grant(id,from,to,parent,overrides={}){return api.createDelegationGrantRevisionV1({grant_id:id,tenant_id:"tenant-1",revision:1,delegator:agent(from),delegate:agent(to),authority_bounds:bounds(),valid_from:10,expires_at:100,onward_delegation_allowed:!parent,max_delegation_depth:2,...(parent?{parent_grant_ref:parent.ref,ancestry_grant_refs:[parent.ref],depth:2}:{ancestry_grant_refs:[],depth:1}),governing_authority_refs:[],governing_policy_refs:[],approval_refs:[],provenance_refs:[],issued_by:"governance",issued_at:10,reason:"test",...overrides})}
const head=(r,overrides={})=>api.validateDelegationGrantHeadV1({schema_version:api.ACS_NATIVE_SCHEMA_VERSION,grant_id:r.ref.grant_id,tenant_id:"tenant-1",current_revision:1,current_fingerprint:r.ref.fingerprint,lifecycle:"active",valid_from:10,expires_at:100,created_at:10,updated_at:10,...overrides});
const source={tenant_id:"tenant-1",authority_bounds:bounds(),valid_from:1,expires_at:200,onward_delegation_allowed:true,max_delegation_depth:2,governing_authority_refs:[],governing_policy_refs:[]};
function resolver(entries, owner={async resolveDelegatorAuthority(){return source}}){return new api.DurableDelegationAuthorityResolverV1({async getDelegationGrantLineage(id){const item=entries.get(id);if(!item)throw new Error("missing");return item}},owner)}

test("Slice 3 resolves one exact A-to-B-to-C chain and preserves its single basis",async()=>{const ab=grant("ab","agent-a","agent-b");const bc=grant("bc","agent-b","agent-c",ab);const r=resolver(new Map([["ab",{head:head(ab),revisions:[ab],revocations:[]}],["bc",{head:head(bc),revisions:[bc],revocations:[]}]]));const out=await r.resolve({grant_ref:bc.ref,at:20});assert.deepEqual(out.chain.map(x=>x.revision.ref.grant_id),["ab","bc"]);assert.equal(out.authority_basis.revision.ref.grant_id,"bc");assert.deepEqual(out.effective_authority.authority_bounds.actions,["read"])});

test("Slice 3 fails closed for ancestor lifecycle, missing/fingerprint/Tenant, and unavailable owner",async()=>{const ab=grant("ab","agent-a","agent-b");const bc=grant("bc","agent-b","agent-c",ab);const entries=new Map([["ab",{head:head(ab,{lifecycle:"revoked",revoked_at:30,revocation_reason:"x",updated_at:30}),revisions:[ab],revocations:[]}],["bc",{head:head(bc),revisions:[bc],revocations:[]}]]);await assert.rejects(()=>resolver(entries).resolve({grant_ref:bc.ref,at:40}),api.DelegationResolutionError);assert.equal((await Promise.resolve(entries.get("ab"))).revisions[0].ref.fingerprint,ab.ref.fingerprint);await assert.rejects(()=>resolver(new Map()).resolve({grant_ref:bc.ref,at:20}),api.DelegationResolutionError);await assert.rejects(()=>resolver(new Map([["ab",{head:head(ab),revisions:[ab],revocations:[]}],["bc",{head:{...head(bc),tenant_id:"tenant-2"},revisions:[bc],revocations:[]}]] )).resolve({grant_ref:bc.ref,at:20}),api.DelegationResolutionError);await assert.rejects(()=>resolver(new Map([["ab",{head:head(ab),revisions:[ab],revocations:[]}],["bc",{head:head(bc),revisions:[bc],revocations:[]}]]),{async resolveDelegatorAuthority(){throw new Error("down")}}).resolve({grant_ref:bc.ref,at:20}),api.DelegationResolutionError)});

test("Slice 3 fails closed when an otherwise valid child has an expired ancestor",async()=>{const ab=grant("ab","agent-a","agent-b",undefined,{expires_at:15});const bc=grant("bc","agent-b","agent-c",ab);const entries=new Map([["ab",{head:head(ab,{expires_at:15}),revisions:[ab],revocations:[]}],["bc",{head:head(bc),revisions:[bc],revocations:[]}]]);await assert.rejects(()=>resolver(entries).resolve({grant_ref:bc.ref,at:20}),(e)=>e instanceof api.DelegationResolutionError&&e.code==="GRANT_NOT_USABLE")});

test("Slice 3 fails closed when a parent revision fingerprint does not match",async()=>{const ab=grant("ab","agent-a","agent-b");const expected={...ab.ref,fingerprint:hash("f")};const bc=grant("bc","agent-b","agent-c",ab,{parent_grant_ref:expected,ancestry_grant_refs:[expected]});const entries=new Map([["ab",{head:head(ab),revisions:[ab],revocations:[]}],["bc",{head:head(bc),revisions:[bc],revocations:[]}]]);await assert.rejects(()=>resolver(entries).resolve({grant_ref:bc.ref,at:20}),(e)=>e instanceof api.DelegationResolutionError&&e.code==="AUTHORITY_REFERENCE_UNRESOLVED")});

test("Slice 3 rejects expansion and cannot merge independent authority or multiple Grants",async()=>{const ab=grant("ab","agent-a","agent-b");const expanded=grant("bc","agent-b","agent-c",ab,{authority_bounds:bounds(["read","write"])});const entries=new Map([["ab",{head:head(ab),revisions:[ab],revocations:[]}],["bc",{head:head(expanded),revisions:[expanded],revocations:[]}]]);await assert.rejects(()=>resolver(entries).resolve({grant_ref:expanded.ref,at:20}),(e)=>e instanceof api.DelegationResolutionError&&e.code==="AUTHORITY_ATTENUATION_DENIED");assert.throws(()=>api.selectDelegationAuthorityBasisV1([{revision:ab,head:head(ab)},{revision:expanded,head:head(expanded)}]),api.DelegationResolutionError)});
