import assert from "node:assert/strict";
import test from "node:test";
import { Pool } from "pg";

const api = await import(`${process.env.ACS_TEST_DIST_ROOT ?? "../dist"}/index.js`);
const hash="a".repeat(64);
async function isolated(run) { const schema=`e17i03as3_${Date.now()}_${process.pid}`; const admin=new Pool({connectionString:process.env.ACS_SH_DATABASE_URL}); const url=new URL(process.env.ACS_SH_DATABASE_URL); url.searchParams.set("options",`-c search_path=${schema}`); const state=new api.PostgresSharedAuthoritativeState({connectionString:url.toString()}); const pool=new Pool({connectionString:url.toString()}); try { await admin.query(`CREATE SCHEMA "${schema}"`); await state.migrate(); await pool.query("INSERT INTO acs_tenants (tenant_id, revision, payload) VALUES ('tenant-a',1,'{}'::jsonb)"); await run(state,pool); } finally { await state.close().catch(()=>undefined); await pool.end().catch(()=>undefined); await admin.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`); await admin.end(); } }
function event(id,seq,type,subjectType,subjectId,payload) { return api.createEventEnvelopeV2({event_id:id,event_type:type,timestamp:seq,sequence:seq,organization_id:"org",product_domain:"acs",tenant_id:"tenant-a",subject_type:subjectType,subject_id:subjectId,actor:{kind:"service",ref:"test"},source:"acs",correlation_id:id,idempotency_key:id,payload}); }
function connection() { const definition=api.createIntegrationConnectionDefinitionV1({connection_id:"connection-a",tenant_id:"tenant-a",connector_definition_ref:"resource:mcp",lifecycle:"active",current_revision:1,created_at:1,updated_at:1}); const revision=api.createIntegrationConnectionRevisionV1({connection_id:"connection-a",revision:1,connector_definition_ref:"resource:mcp",configuration:{transport:"https"},credential_ref:{credential_ref:"credential-a",credential_version:"v1",secret_store_ref:"vault-a"},lifecycle:"active",commit:{created_by:"test",committed_at:1,change_reason:"test"}}); return {definition,revision}; }
function channel(connectionRef) { const definition=api.createIntegrationChannelDefinitionV1({channel_id:"channel-a",tenant_id:"tenant-a",lifecycle:"active",current_revision:1,created_at:1,updated_at:1}); const revision=api.createIntegrationChannelRevisionV1({channel_id:"channel-a",revision:1,connection_revision_ref:connectionRef,direction:"ingress",endpoint:{kind:"webhook",uri:"https://provider.test/ingress"},lifecycle:"active",commit:{created_by:"test",committed_at:1,change_reason:"test"}}); return {definition,revision}; }
function ingress(reference,id,sequence,outboxId) { const payload={ingress_ref:reference.ingress_ref,channel_revision_ref:api.serializeNative(reference.channel_revision_ref),connection_revision_ref:api.serializeNative(reference.connection_revision_ref),payload_digest:reference.payload_digest,authentication_method:reference.authentication_method}; const ingressEvent=event(id,sequence,"integration.channel.ingress_authenticated","integration_channel","channel-a",payload); const evidence=api.createEvidenceRecordV2({evidence_id:`evidence-${id}`,kind:"decision",subject_ref:{kind:"integration_channel",id:"channel-a"},event_ref:{kind:"event",id},source:"provider",classification:"restricted",payload_digest:reference.payload_digest,created_at:sequence,provenance:{ingress_ref:reference.ingress_ref,authentication_method:reference.authentication_method,channel_revision_ref:reference.channel_revision_ref,connection_revision_ref:reference.connection_revision_ref,correlation_id:reference.correlation_id,result:"authenticated"}}); return {reference,event:ingressEvent,evidence,outboxId}; }

test("Slice 3 persists authenticated ingress Event, Evidence, and outbox atomically without execution state",{skip:process.env.ACS_SH_DATABASE_URL?false:"ACS_SH_DATABASE_URL is not configured"},async()=>{
  await isolated(async(state,pool)=>{ const c=connection(); await state.nativeCore.advanceIntegrationConnectionLineage({definition:c.definition,revision:c.revision,expectedHead:0,idempotency:{scope:"integration.connection:connection-a",key:"create",request_hash:hash},event:event("connection-created",1,"integration.connection.created","integration_connection","connection-a",{revision:1,fingerprint:c.revision.ref.fingerprint}),outboxId:"connection-outbox"}); const ch=channel(c.revision.ref); await state.nativeCore.advanceIntegrationChannelLineage({definition:ch.definition,revision:ch.revision,expectedHead:0,idempotency:{scope:"integration.channel:channel-a",key:"create",request_hash:hash},event:event("channel-created",1,"integration.channel.created","integration_channel","channel-a",{revision:1,fingerprint:ch.revision.ref.fingerprint}),outboxId:"channel-outbox"}); const reference=api.validateAuthenticatedIntegrationIngressReferenceV1({schema_version:"1.0",ingress_ref:"ingress-a",tenant_id:"tenant-a",channel_revision_ref:ch.revision.ref,connection_revision_ref:c.revision.ref,credential_ref:"credential-a",credential_version:"v1",authentication_method:"hmac-sha256",payload_digest:"b".repeat(64),correlation_id:"correlation-a",authenticated_at:2}); const recorded=await state.nativeCore.recordAuthenticatedIntegrationIngress(ingress(reference,"ingress-event-a",2,"ingress-outbox")); assert.equal(recorded.event.streamScope,"integration-channel:channel-a"); assert.equal(recorded.evidence.provenance.result,"authenticated"); assert.equal((await state.nativeCore.getRun("anything")),undefined); const before=await pool.query("SELECT (SELECT count(*) FROM acs_native_events)::int AS events,(SELECT count(*) FROM acs_native_evidence)::int AS evidence,(SELECT count(*) FROM acs_native_outbox)::int AS outbox"); await assert.rejects(()=>state.nativeCore.recordAuthenticatedIntegrationIngress(ingress({...reference,ingress_ref:"ingress-b",correlation_id:"correlation-b"},"ingress-event-b",3,"ingress-outbox"))); const after=await pool.query("SELECT (SELECT count(*) FROM acs_native_events)::int AS events,(SELECT count(*) FROM acs_native_evidence)::int AS evidence,(SELECT count(*) FROM acs_native_outbox)::int AS outbox"); assert.deepEqual(after.rows[0],before.rows[0]); });
});
